### ISSUE TITLE
大大好；这个jd_shell/panel/面板可以搬嘛

### ISSUE THREAD

**Issue by dockere** [nevinee/jd_shell#6]
jd_shell/panel/可以搬嘛，或者回归也行啊。

**Comment by SuperManito** [comment]
+1

**Comment by nevinee** [comment]
算回归吧，只是不想传得太远。

**Comment by dockere** [comment]
> 算回归吧，只是不想传得太远。

在群里吗，我镜像关了吧。

**Comment by nevinee** [comment]
> > 算回归吧，只是不想传得太远。
> 
> 在群里吗，我镜像关了吧。

无所谓的

**Comment by dockere** [comment]
或交给你维护也行啊，只是用的人太多了；群里都想你回来呢，我私聊你github密码

**Comment by nevinee** [comment]
> 或交给你维护也行啊，只是用的人太多了；群里都想你回来呢，我私聊你github密码

不用不用，真不用。

**Comment by dockere** [comment]
> > 或交给你维护也行啊，只是用的人太多了；群里都想你回来呢，我私聊你github密码
> 
> 不用不用，真不用。

好吧。- -

**Comment by dockere** [comment]
期待群里冒泡😁
